name: Deploy to Server

on:
  push:
    branches:
      - main  # или твой основной branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v2

      # Шаг 2: Настроим SSH доступ
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Шаг 3: Выполняем деплой на сервер
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no user@your-server-ip 'cd /path/to/your/project && git pull origin main && npm install && pm2 restart your-app'
